name: Publish
on:
  release:
    types: [published]
jobs:
  test:
    uses: ./.github/workflows/test.yml
  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
      - name: Build
        run: 
          echo "SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV
          uv build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/
          name: wordsearch-package


  publish-pypi:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: dist/
          name: wordsearch-package
      - name: Push to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
