name: Publish
on:
  release:
    types: [published]
  push:
jobs:
  test:
    uses: ./.github/workflows/test.yml
  build_and_publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
      - run: echo "SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV
      - run: uv build
      - uses: actions/upload-artifact@v4
        with:
          path: ./dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ./dist
#
#  publish-pypi:
#    needs:
#      build
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/download-artifact@@v4
#      - uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          packages-dir: artifact/