name: Tests
permissions:
  contents: read
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/test.yml"
      - "src/**"
      - "tests/**"
      - "pyproject.toml"
jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5.4.2
      - name: Run Ruff
        run: uv run ruff check --output-format=github .
      - name: Ruff format
        run: uv run ruff format . --check
  test-against-python-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
      fail-fast: true
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5.4.2
      - name: Run tests
        run: |
          uv run -p ${{ matrix.python-version }} pytest
