name: Test Build
on:
  workflow_call:
  workflow_dispatch:
  push:
jobs:
  test:
    uses: ./.github/workflows/test.yml
  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
      - name: Build
        run: |
          echo "SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV
          uv build
          ls dist/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/
          name: wordsearch-package
